 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/application_settings", type: :request do
  
  # ApplicationSetting. As you add validations to ApplicationSetting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ApplicationSetting.create! valid_attributes
      get application_settings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      application_setting = ApplicationSetting.create! valid_attributes
      get application_setting_url(application_setting)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_application_setting_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      application_setting = ApplicationSetting.create! valid_attributes
      get edit_application_setting_url(application_setting)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ApplicationSetting" do
        expect {
          post application_settings_url, params: { application_setting: valid_attributes }
        }.to change(ApplicationSetting, :count).by(1)
      end

      it "redirects to the created application_setting" do
        post application_settings_url, params: { application_setting: valid_attributes }
        expect(response).to redirect_to(application_setting_url(ApplicationSetting.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ApplicationSetting" do
        expect {
          post application_settings_url, params: { application_setting: invalid_attributes }
        }.to change(ApplicationSetting, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post application_settings_url, params: { application_setting: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested application_setting" do
        application_setting = ApplicationSetting.create! valid_attributes
        patch application_setting_url(application_setting), params: { application_setting: new_attributes }
        application_setting.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the application_setting" do
        application_setting = ApplicationSetting.create! valid_attributes
        patch application_setting_url(application_setting), params: { application_setting: new_attributes }
        application_setting.reload
        expect(response).to redirect_to(application_setting_url(application_setting))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        application_setting = ApplicationSetting.create! valid_attributes
        patch application_setting_url(application_setting), params: { application_setting: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested application_setting" do
      application_setting = ApplicationSetting.create! valid_attributes
      expect {
        delete application_setting_url(application_setting)
      }.to change(ApplicationSetting, :count).by(-1)
    end

    it "redirects to the application_settings list" do
      application_setting = ApplicationSetting.create! valid_attributes
      delete application_setting_url(application_setting)
      expect(response).to redirect_to(application_settings_url)
    end
  end
end
