 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dpa_exceptions", type: :request do
  
  # DpaException. As you add validations to DpaException, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DpaException.create! valid_attributes
      get dpa_exceptions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dpa_exception = DpaException.create! valid_attributes
      get dpa_exception_url(dpa_exception)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dpa_exception_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      dpa_exception = DpaException.create! valid_attributes
      get edit_dpa_exception_url(dpa_exception)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DpaException" do
        expect {
          post dpa_exceptions_url, params: { dpa_exception: valid_attributes }
        }.to change(DpaException, :count).by(1)
      end

      it "redirects to the created dpa_exception" do
        post dpa_exceptions_url, params: { dpa_exception: valid_attributes }
        expect(response).to redirect_to(dpa_exception_url(DpaException.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DpaException" do
        expect {
          post dpa_exceptions_url, params: { dpa_exception: invalid_attributes }
        }.to change(DpaException, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dpa_exceptions_url, params: { dpa_exception: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dpa_exception" do
        dpa_exception = DpaException.create! valid_attributes
        patch dpa_exception_url(dpa_exception), params: { dpa_exception: new_attributes }
        dpa_exception.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dpa_exception" do
        dpa_exception = DpaException.create! valid_attributes
        patch dpa_exception_url(dpa_exception), params: { dpa_exception: new_attributes }
        dpa_exception.reload
        expect(response).to redirect_to(dpa_exception_url(dpa_exception))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        dpa_exception = DpaException.create! valid_attributes
        patch dpa_exception_url(dpa_exception), params: { dpa_exception: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dpa_exception" do
      dpa_exception = DpaException.create! valid_attributes
      expect {
        delete dpa_exception_url(dpa_exception)
      }.to change(DpaException, :count).by(-1)
    end

    it "redirects to the dpa_exceptions list" do
      dpa_exception = DpaException.create! valid_attributes
      delete dpa_exception_url(dpa_exception)
      expect(response).to redirect_to(dpa_exceptions_url)
    end
  end
end
