 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/legacy_os_records", type: :request do
  
  # LegacyOsRecord. As you add validations to LegacyOsRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LegacyOsRecord.create! valid_attributes
      get legacy_os_records_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      legacy_os_record = LegacyOsRecord.create! valid_attributes
      get legacy_os_record_url(legacy_os_record)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_legacy_os_record_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      legacy_os_record = LegacyOsRecord.create! valid_attributes
      get edit_legacy_os_record_url(legacy_os_record)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LegacyOsRecord" do
        expect {
          post legacy_os_records_url, params: { legacy_os_record: valid_attributes }
        }.to change(LegacyOsRecord, :count).by(1)
      end

      it "redirects to the created legacy_os_record" do
        post legacy_os_records_url, params: { legacy_os_record: valid_attributes }
        expect(response).to redirect_to(legacy_os_record_url(LegacyOsRecord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LegacyOsRecord" do
        expect {
          post legacy_os_records_url, params: { legacy_os_record: invalid_attributes }
        }.to change(LegacyOsRecord, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post legacy_os_records_url, params: { legacy_os_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested legacy_os_record" do
        legacy_os_record = LegacyOsRecord.create! valid_attributes
        patch legacy_os_record_url(legacy_os_record), params: { legacy_os_record: new_attributes }
        legacy_os_record.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the legacy_os_record" do
        legacy_os_record = LegacyOsRecord.create! valid_attributes
        patch legacy_os_record_url(legacy_os_record), params: { legacy_os_record: new_attributes }
        legacy_os_record.reload
        expect(response).to redirect_to(legacy_os_record_url(legacy_os_record))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        legacy_os_record = LegacyOsRecord.create! valid_attributes
        patch legacy_os_record_url(legacy_os_record), params: { legacy_os_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested legacy_os_record" do
      legacy_os_record = LegacyOsRecord.create! valid_attributes
      expect {
        delete legacy_os_record_url(legacy_os_record)
      }.to change(LegacyOsRecord, :count).by(-1)
    end

    it "redirects to the legacy_os_records list" do
      legacy_os_record = LegacyOsRecord.create! valid_attributes
      delete legacy_os_record_url(legacy_os_record)
      expect(response).to redirect_to(legacy_os_records_url)
    end
  end
end
