 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sensitive_data_systems", type: :request do
  
  # SensitiveDataSystem. As you add validations to SensitiveDataSystem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SensitiveDataSystem.create! valid_attributes
      get sensitive_data_systems_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sensitive_data_system = SensitiveDataSystem.create! valid_attributes
      get sensitive_data_system_url(sensitive_data_system)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sensitive_data_system_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      sensitive_data_system = SensitiveDataSystem.create! valid_attributes
      get edit_sensitive_data_system_url(sensitive_data_system)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SensitiveDataSystem" do
        expect {
          post sensitive_data_systems_url, params: { sensitive_data_system: valid_attributes }
        }.to change(SensitiveDataSystem, :count).by(1)
      end

      it "redirects to the created sensitive_data_system" do
        post sensitive_data_systems_url, params: { sensitive_data_system: valid_attributes }
        expect(response).to redirect_to(sensitive_data_system_url(SensitiveDataSystem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SensitiveDataSystem" do
        expect {
          post sensitive_data_systems_url, params: { sensitive_data_system: invalid_attributes }
        }.to change(SensitiveDataSystem, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sensitive_data_systems_url, params: { sensitive_data_system: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sensitive_data_system" do
        sensitive_data_system = SensitiveDataSystem.create! valid_attributes
        patch sensitive_data_system_url(sensitive_data_system), params: { sensitive_data_system: new_attributes }
        sensitive_data_system.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sensitive_data_system" do
        sensitive_data_system = SensitiveDataSystem.create! valid_attributes
        patch sensitive_data_system_url(sensitive_data_system), params: { sensitive_data_system: new_attributes }
        sensitive_data_system.reload
        expect(response).to redirect_to(sensitive_data_system_url(sensitive_data_system))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        sensitive_data_system = SensitiveDataSystem.create! valid_attributes
        patch sensitive_data_system_url(sensitive_data_system), params: { sensitive_data_system: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sensitive_data_system" do
      sensitive_data_system = SensitiveDataSystem.create! valid_attributes
      expect {
        delete sensitive_data_system_url(sensitive_data_system)
      }.to change(SensitiveDataSystem, :count).by(-1)
    end

    it "redirects to the sensitive_data_systems list" do
      sensitive_data_system = SensitiveDataSystem.create! valid_attributes
      delete sensitive_data_system_url(sensitive_data_system)
      expect(response).to redirect_to(sensitive_data_systems_url)
    end
  end
end
