default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: root
  password: <%= ENV['LOCAL_MYSQL_DATABASE_PASSWORD'] %>
  database: vodst_development

test:
  <<: *default
  username: root
  password: <%= ENV['LOCAL_MYSQL_DATABASE_PASSWORD'] %>
  database: vodst_test

production:
  <<: *default
  database: vodsecurityproduction
  username: <%= Rails.application.credentials.mysql[:prod_user] %>
  password: <%= Rails.application.credentials.mysql[:prod_password] %>
  host: <%= Rails.application.credentials.mysql[:prod_servername] %>
  sslmode: require
  sslca: <%= Rails.application.credentials.mysql[:prod_sslca] %>
